name: Build and Push to AWS ECR

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_REPO=${{ secrets.ECR_REPOSITORY }}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=${{ secrets.AWS_REGION }}
          IMAGE_BASE=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO

          docker build -t $IMAGE_REPO .

          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # Cas release → seulement le tag version
            VERSION=${GITHUB_REF#refs/tags/}
            docker tag $IMAGE_REPO $IMAGE_BASE:$VERSION
            docker push $IMAGE_BASE:$VERSION

            # Optionnel : latest si c’est la prod
            docker tag $IMAGE_REPO $IMAGE_BASE:latest
            docker push $IMAGE_BASE:latest
          else
            # Cas normal → dev ou main
            COMMIT_SHA=${{ github.sha }}
            BRANCH_NAME=${GITHUB_REF##*/}

            docker tag $IMAGE_REPO $IMAGE_BASE:sha-${COMMIT_SHA}
            docker push $IMAGE_BASE:sha-${COMMIT_SHA}

            docker tag $IMAGE_REPO $IMAGE_BASE:branch-${BRANCH_NAME}
            docker push $IMAGE_BASE:branch-${BRANCH_NAME}

            if [ "$BRANCH_NAME" = "main" ]; then
              docker tag $IMAGE_REPO $IMAGE_BASE:latest
              docker push $IMAGE_BASE:latest
            fi
          fi
